name: Selenium CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports
